theme = "earl_grey"

[editor]
true-color = true
line-number = "relative"
rulers = [90]
        
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"] # deselect all; keep primary cursor only
