# [language-server.expert]
# command = "/home/cr0xd/.local/bin/expert"

[[language]]
name = "elixir"
language-servers = ["elixir-ls"]
# language-servers = ["expert"]

[[language]]
name = "heex"
language-servers = ["elixir-ls"]
# language-servers = ["expert"]

[[language]]
name = "python"
auto-format = true
language-servers = ["jedi-language-server"]

[language-server.jedi-language-server]
command = "./.venv/bin/jedi-language-server"

[[language]]
name = "typescript"
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "tsx"
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server"]
auto-format = true
