# ----------
#
# Ref: https://docs.helix-editor.com/themes.html
#
# ----------
#
# Modifiers
#   bold
#   dim
#   italic
#   underlined
#   slow_blink
#   rapid_blink
#   reversed
#   hidden
#   crossed_out
#
# ----------
#
# Underline style
#   line
#   curl
#   dashed
#   dotted
#   double_line
#
# ----------

"ui.background"              = { bg = "background" }
"ui.text"                    = { fg = "foreground" }
"ui.cursor"                  = { fg = "background", bg = "green" }
"ui.cursor.match"            = { fg = "background", bg = "dark_green" }
# "ui.cursor.primary.insert"   = { modifiers = ["slow_blink"] } # "bar" does not support fg / bg
# "ui.cursor.primary.normal"   = { fg = "background", bg = "green" }
# "ui.cursor.primary.select"   = { fg = "background", bg = "green" }
"ui.selection"               = { fg = "foreground", bg = "dark_green" }

"string"             = { fg = "brown" }
"constant.numeric"   = { fg = "brown" }

"comment"            = { fg = "light_grey" }
"keyword"            = { fg = "light_grey" }
"punctuation"        = { fg = "light_grey" }
"operator"           = { fg = "light_grey" }

"ui.linenr"          = { fg = "light_grey", modifiers = ["dim"] }
"ui.linenr.selected" = { fg = "light_grey", modifiers = ["dim", "bold"] }

"ui.virtual.ruler"   = { bg = "dark_grey" }

# diagnostic
"error"                = { fg = "error" }
"warning"              = { fg = "warning" }
"info"                 = { fg = "info" }
"hint"                 = { fg = "hint" }
"diagnostic.error"     = { fg = "foreground", bg = "background", underline = { style = "curl", color = "error" } }
"diagnostic.warning"   = { fg = "foreground", bg = "background", underline = { style = "curl", color = "warning" } }
"diagnostic.info"      = { fg = "foreground", bg = "background", underline = { style = "curl", color = "info" } }
"diagnostic.hint"      = { fg = "foreground", bg = "background", underline = { style = "curl", color = "hint" } }

# markdown
"markup.link"            = { modifiers = ["dim"] }
"markup.quote"           = { modifiers = ["dim"] }
"markup.heading"         = { fg = "brown" }
"markup.heading.marker"  = { fg = "light_grey" }
"markup.raw"             = { fg = "light_grey" }
"markup.list"            = { fg = "light_grey" }

"markup.normal.completion" = { fg = "foreground"}
"markup.normal.hover"      = { fg = "brown"}

[palette]

background = "#161616"
foreground = "#d9c9ac"   # dimmed
# foreground = "#f2e0c0" # bright

light_grey = "#666666"
dark_grey  = "#191919"

yellow     = "#f2e0c0"
brown      = "#ac7151"
pink       = "#fdc0ce"
green      = "#51ac71"
dark_green = "#285638"

# diagnostic
error      = "#ce4141"
warning    = "#cece41"
info       = "#4141ce"
hint       = "#666666"
