"ui.background"      = { bg = "background" }
"ui.text"            = { fg = "foreground" }
"ui.selection"       = { bg = "foreground", fg = "background" }

"string"             = { fg = "brown" }
"constant.numeric"   = { fg = "brown" }

"comment"            = { fg = "light_grey" }
"keyword"            = { fg = "light_grey" }
"punctuation"        = { fg = "light_grey" }
"operator"           = { fg = "light_grey" }

"ui.linenr"          = { fg = "light_grey" }
"ui.linenr.selected" = { fg = "light_grey", modifiers = ["bold"] }

"ui.virtual.ruler"   = { bg = "dark_grey" }

# diagnostic
"error"              = { fg = "red" }
"diagnostic.error"   = { fg = "foreground", bg = "background", underline = { style = "curl", color = "red" } }

# markdown
"markup.link.url" = { modifiers = ["underlined"] }
"markup.quote"    = "brown"
"markup.raw"      = "light_grey"

[palette]

background = "#161616"
foreground = "#f2e0c0"

light_grey = "#666666"
dark_grey  = "#191919"

yellow     = "#f2e0c0"
red        = "#ce4141"
brown      = "#ac7151"
pink       = "#fdc0ce"
