#!/usr/bin/env bash

src=/home/cr0xd/main
dest_local=/home/cr0xd/main_backup.tar.gz
src_paths=(
  "/home/cr0xd/main"
  "/home/cr0xd/.ssh"
  "/home/cr0xd/art/ai/shared/workflows"
)
dest_paths=(
  "/media/disk/"
  "/media/usb/"
)

set -euo pipefail

# Check if root
uid=$(id -u)
if (( uid != 0 )); then
  echo "--- Skipping - requires root privileges."
  exit
fi

if [[ ! -e /dev/sda ]]; then
  echo "--- Skipping - Hard Drive not present."
  exit
fi

if [[ ! -e /dev/disk/by-label/backup ]]; then
  echo "--- Skipping - USB not present."
  exit
fi

sudo mount /dev/sda /media/disk
sudo mount /dev/disk/by-label/backup /media/usb



echo
echo "=== Backup to ${dest_local}"
tar -c -f - ${src} -P \
  | pv -s $(du -sb ${src} | awk '{print $1}') \
  | gzip > ${dest_local}



for dest in "${dest_paths[@]}"; do
  echo
  echo "=== Backup to ${dest}"

  for src in "${src_paths[@]}"; do
    echo ${src}

    size=$(rsync -av --delete --dry-run ${src} ${dest} | wc -l)
    rsync -av --delete ${src} ${dest} | pv -l -s ${size} > /dev/null
  done
done

echo
echo "=== Cleanup"
sudo umount /media/disk
sudo umount /media/usb
